version: '3.11'
services:
  django:
    build:
      context: ./fishing_project
      dockerfile: Dockerfile-django
    container_name: django-server
    ports:
      - "8000:8000"
    volumes:
      - ./fishing_project:/app
    depends_on:
      - db

  flask:
    build:
      context: ./client
      dockerfile: Dockerfile-flask
    container_name: flask-client
    ports:
      - "5000:5000"
    environment:
      DJANGO_API_URL: http://django-server:8000
    depends_on:
      - django

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
